### ISSUE TITLE
Characters without custom sound files cannot have their attacks interpreted by RoABox.

### ISSUE THREAD

**Issue by Ethy202** [fudgepop01/Rivals-of-Aether-GML#2]
A custom character that uses only sounds already existing in RoA are rare, but they can't have their attacks interpreted by RoABox as the folder that holds sounds for them doesn't exist, and therefore RoABox simply refuses to interpret moves from these characters. An empty sound folder works, but doesn't play sounds. Having the extension either ask for the default sound library as well as the custom character sound library would fix this issue.

**Comment by fudgepop01** [comment]
Hello! Thanks for using the extension and filing a report! :D

I tried to add support for sounds, but there were a few things that made me decide against it:

For better or worse, Visual Studio Code does not have the capacity to play sounds by default. To enable sounds, I would need to:
1. include all the default sounds in the game, pushing the size of the extension to over 250mb
2. include an audio player - which in _theory_ works, but the sounds can be significantly out of sync.

It is because of these two things that I believe it's better to try to make a sound test utility of sorts that you can use to pick and choose the sounds you desire rather than having me include everything in the extension, leading to issues with synchronizing sounds to the proper frames.
